### ISSUE TITLE
How to jump to nth index page ? 

### ISSUE THREAD

**Issue by RonnyCoder** [policante/PageControl#2]
How to load nth indexed page ?

**Comment by RonnyCoder** [comment]
Got solution but its not appropriate. need to call that much(index) times nextPage() PreviousPage().
Please provide proper solution for the same. 
Thanks A a lot

**Comment by policante** [comment]
I'll provide the solution to this problem
Thanks for the suggestion.

**Comment by RonnyCoder** [comment]
Thanks a lot.  
Sorry for being greedy.  Can you please try to provide it as early as possible.
As I have around 30/35 pages and with this current implementation app performance is lacking.

**Comment by RonnyCoder** [comment]
Hi Policante, 
any update on this ?
thanks

**Comment by policante** [comment]
Solved with last commit :)

**Comment by RonnyCoder** [comment]
Thanks A Lot. 
can you please update pod version. Thanks
Updated version missing on Pod

**Comment by policante** [comment]
done :}
